"""fintech_payments

Revision ID: 139dba0b8c81
Revises: 185d25001268
Create Date: 2026-06-22 19:51:35.865084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '139dba0b8c81'
down_revision: Union[str, Sequence[str], None] = '185d25001268'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('conversation_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('kind', sa.Enum('GIVEAWAY_SETUP', 'WINNER_PAYOUT', name='conversationkind'), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('thread_tweet_id', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('draft_json', sa.Text(), nullable=False),
    sa.Column('related_giveaway_id', sa.String(), nullable=True),
    sa.Column('related_winner_id', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['related_giveaway_id'], ['giveaways.id'], ),
    sa.ForeignKeyConstraint(['related_winner_id'], ['winners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversation_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversation_sessions_thread_tweet_id'), ['thread_tweet_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('payment_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('external_reference', sa.String(), nullable=True),
    sa.Column('giveaway_id', sa.String(), nullable=True),
    sa.Column('winner_id', sa.String(), nullable=True),
    sa.Column('amount_kobo', sa.Integer(), nullable=True),
    sa.Column('raw_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['giveaway_id'], ['giveaways.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['winners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_events_external_reference'), ['external_reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_events_giveaway_id'), ['giveaway_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_events_provider'), ['provider'], unique=False)

    with op.batch_alter_table('giveaways', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount_kobo', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('amount_received_kobo', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('funding_status', sa.Enum('NOT_REQUIRED', 'AWAITING_PAYMENT', 'FUNDED', 'EXPIRED', 'UNDERPAID', 'OVERPAID', name='fundingstatus'), nullable=False))
        batch_op.add_column(sa.Column('payment_provider', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('va_provider_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('va_account_number', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('va_bank_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('va_account_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('va_external_reference', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('va_expires_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('funded_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_giveaways_va_external_reference'), ['va_external_reference'], unique=False)

    with op.batch_alter_table('winners', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payout_status', sa.Enum('NOT_STARTED', 'COLLECTING_DETAILS', 'VERIFYING', 'READY', 'PROCESSING', 'PAID', 'FAILED', name='payoutstatus'), nullable=False))
        batch_op.add_column(sa.Column('payout_amount_kobo', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bank_code', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('bank_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('account_number', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('account_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('name_enquiry_ref', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('payout_reference', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('payout_provider', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_winners_payout_reference'), ['payout_reference'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('winners', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_winners_payout_reference'))
        batch_op.drop_column('paid_at')
        batch_op.drop_column('payout_provider')
        batch_op.drop_column('payout_reference')
        batch_op.drop_column('name_enquiry_ref')
        batch_op.drop_column('account_name')
        batch_op.drop_column('account_number')
        batch_op.drop_column('bank_name')
        batch_op.drop_column('bank_code')
        batch_op.drop_column('payout_amount_kobo')
        batch_op.drop_column('payout_status')

    with op.batch_alter_table('giveaways', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_giveaways_va_external_reference'))
        batch_op.drop_column('funded_at')
        batch_op.drop_column('va_expires_at')
        batch_op.drop_column('va_external_reference')
        batch_op.drop_column('va_account_name')
        batch_op.drop_column('va_bank_name')
        batch_op.drop_column('va_account_number')
        batch_op.drop_column('va_provider_id')
        batch_op.drop_column('payment_provider')
        batch_op.drop_column('funding_status')
        batch_op.drop_column('amount_received_kobo')
        batch_op.drop_column('amount_kobo')

    with op.batch_alter_table('payment_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_events_provider'))
        batch_op.drop_index(batch_op.f('ix_payment_events_giveaway_id'))
        batch_op.drop_index(batch_op.f('ix_payment_events_external_reference'))

    op.drop_table('payment_events')
    with op.batch_alter_table('conversation_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_conversation_sessions_thread_tweet_id'))

    op.drop_table('conversation_sessions')
    op.drop_table('system_settings')
    # ### end Alembic commands ###
