"""add_pick_seed

Revision ID: 185d25001268
Revises: 332da065c1b1
Create Date: 2026-06-22 19:31:11.824865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '185d25001268'
down_revision: Union[str, Sequence[str], None] = '332da065c1b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('giveaways', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pick_seed', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('giveaways', schema=None) as batch_op:
        batch_op.drop_column('pick_seed')

    # ### end Alembic commands ###
