"""initial_schema

Revision ID: 332da065c1b1
Revises: 
Create Date: 2026-06-22 19:25:13.888531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '332da065c1b1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cursors',
    sa.Column('stream_key', sa.String(), nullable=False),
    sa.Column('since_id', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('stream_key')
    )
    op.create_table('giveaways',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('host_tweet_id', sa.String(), nullable=True),
    sa.Column('host_user_id', sa.String(), nullable=True),
    sa.Column('host_username', sa.String(), nullable=True),
    sa.Column('conversation_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('prize_description', sa.Text(), nullable=True),
    sa.Column('num_winners', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'CLOSED', 'WINNERS_SELECTED', 'COMPLETE', name='giveawaystatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('closes_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('giveaways', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_giveaways_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_giveaways_host_tweet_id'), ['host_tweet_id'], unique=False)

    op.create_table('processed_tweets',
    sa.Column('tweet_id', sa.String(), nullable=False),
    sa.Column('context', sa.String(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('tweet_id')
    )
    op.create_table('sent_dms',
    sa.Column('dedup_key', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('dedup_key')
    )
    op.create_table('entries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('giveaway_id', sa.String(), nullable=False),
    sa.Column('tweet_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('invalid_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['giveaway_id'], ['giveaways.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entries_giveaway_id'), ['giveaway_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_entries_tweet_id'), ['tweet_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_entries_user_id'), ['user_id'], unique=False)

    op.create_table('winners',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('giveaway_id', sa.String(), nullable=False),
    sa.Column('entry_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('SELECTED', 'NOTIFIED', 'DM_FAILED', 'CONFIRMED', 'PAID', name='winnerstatus'), nullable=False),
    sa.Column('selected_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], ),
    sa.ForeignKeyConstraint(['giveaway_id'], ['giveaways.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('winners', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_winners_giveaway_id'), ['giveaway_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_winners_user_id'), ['user_id'], unique=False)

    op.create_table('dm_queue',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('winner_id', sa.String(), nullable=False),
    sa.Column('giveaway_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'SENT', 'FAILED', name='dmqueuestatus'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['giveaway_id'], ['giveaways.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['winners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dm_queue', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dm_queue_giveaway_id'), ['giveaway_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dm_queue_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dm_queue_winner_id'), ['winner_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dm_queue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dm_queue_winner_id'))
        batch_op.drop_index(batch_op.f('ix_dm_queue_user_id'))
        batch_op.drop_index(batch_op.f('ix_dm_queue_giveaway_id'))

    op.drop_table('dm_queue')
    with op.batch_alter_table('winners', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_winners_user_id'))
        batch_op.drop_index(batch_op.f('ix_winners_giveaway_id'))

    op.drop_table('winners')
    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entries_user_id'))
        batch_op.drop_index(batch_op.f('ix_entries_tweet_id'))
        batch_op.drop_index(batch_op.f('ix_entries_giveaway_id'))

    op.drop_table('entries')
    op.drop_table('sent_dms')
    op.drop_table('processed_tweets')
    with op.batch_alter_table('giveaways', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_giveaways_host_tweet_id'))
        batch_op.drop_index(batch_op.f('ix_giveaways_conversation_id'))

    op.drop_table('giveaways')
    op.drop_table('cursors')
    # ### end Alembic commands ###
